package me.dreamhopping.pml.gradle.util

const val EXTENSION_NAME = "minecraft"
const val DOWNLOAD_MANIFEST_NAME = "downloadManifest"
const val DOWNLOAD_VERSION_BASE_NAME = "downloadVersionJson"
const val DOWNLOAD_CLIENT_BASE_NAME = "downloadClient"
const val DOWNLOAD_SERVER_BASE_NAME = "downloadServer"
const val STRIP_CLIENT_BASE_NAME = "stripClient"
const val STRIP_SERVER_BASE_NAME = "stripServer"
const val MERGE_CLASSES_BASE_NAME = "mergeClasses"
const val MERGE_RESOURCES_BASE_NAME = "mergeResources"
const val MAP_BASE_NAME = "mapJar"
const val GENERATE_MAPPINGS_BASE_NAME = "generateMappings"
const val FETCH_YARN_VERSIONS_BASE_NAME = "fetchYarnVersions"
const val DOWNLOAD_YARN_MAPPINGS_BASE_NAME = "downloadYarnMappings"
const val LOAD_MAPPINGS_BASE_NAME = "loadMappings"
const val DOWNLOAD_FERNFLOWER_NAME = "downloadFernflower"
const val GEN_SOURCES_BASE_NAME = "decompile"
const val DOWNLOAD_ASSET_INDEX_BASE_NAME = "downloadAssetIndex"
const val DOWNLOAD_ASSETS_BASE_NAME = "downloadAssets"